[ global ]
    output_path = "../../Outputs/Pong"

[ window ]
    title = "Pong"
    width = 500
    height = 500

[ game ]
    background_colour = "black"
    target_fps = 0
    [ game.components ]
        #[ game.components.title ]
        #    file = "./components/title.jl"
        [ game.components.centre_wall ]
            file = "./components/centre_wall.jl"
        #[ game.components.left_paddle ]
        #    file = "./components/paddle.jl"
        #    args = [ "left" ] 
        #[ game.components.right_paddle ]
        #    file = "./components/paddle.jl"
        #    args = [ "right" ] 
        #[ game.components.ball ]
        #    file = "./components/ball.jl"
   
